### ISSUE TITLE
Some images in blog posts don't appear

### ISSUE THREAD

**Issue by oznogon** [manuel-hegner/paizo-blog-images#1]
Some images in Paizo blog posts don't appear in the tool. Some examples:

- Blog post [Pathfinder Society Year 4 Rule Updates](https://paizo.com/community/blog/v5748dyo6si35) on June 30, 2022: The tool indicates there are [no images]([https://manuel-hegner.github.io/paizo-blog-images/2022-06-all.html) on the post, but it contains an image, the [draught of dreams/PFS Season 3 logo](https://cdn.paizo.com/a7d62ac8-7f03-00ef-f1f0-83fb8bf332e2/6ef4bd9f-ec0c-42f7-9512-dd0b9a9f5047/PFS_ChaliceOnly_Final_NicholasPhillips.png).
- Blog post [A Midsummer Night's Market Meeting](https://paizo.com/community/blog/v5748dyo6si36) on July 6, 2022: The tool [doesn't show the first image](https://manuel-hegner.github.io/paizo-blog-images/2022-07-all.html) in the blog post, the [ichor slinger](https://cdn.paizo.com/a7d62ac8-7f03-00ef-f1f0-83fb8bf332e2/d4358f74-ca01-4276-8b42-aa1453ac2e64/PZO2110_IchorSlinger.jpg).

**Comment by manuel-hegner** [comment]
Images are only shown for the first blog post containing the exact same image. If you sear h in the github repo for the full paizo url of the image you should find a blog post where the image is mentioned. If not that is a real bug. For example the chalice appears first in https://paizo.com/community/blog/v5748dyo6si20
